use crate::ir::{StateDef, WorkflowIR};
use crate::parse::ast::Executor;
use crate::prompt::ParamType;

/// Generate Go code from the workflow IR
pub fn generate(ir: &WorkflowIR) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "// Generated by loom v0.1.0 from {} v{}\n\n",
        ir.name, ir.version
    ));
    out.push_str("package workflow\n\n");
    out.push_str("import \"fmt\"\n\n");

    generate_state_type(ir, &mut out);
    generate_executor_type(&mut out);
    generate_outcome_types(ir, &mut out);
    generate_outcome_union(ir, &mut out);
    generate_apply_fn(ir, &mut out);
    generate_profiles(ir, &mut out);
    generate_prompt_metadata(ir, &mut out);

    out
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase(),
            }
        })
        .collect()
}

fn generate_state_type(ir: &WorkflowIR, out: &mut String) {
    out.push_str("type State int\n\n");
    out.push_str("const (\n");
    for (i, name) in ir.states.keys().enumerate() {
        if i == 0 {
            out.push_str(&format!("\t{} State = iota\n", to_pascal_case(name)));
        } else {
            out.push_str(&format!("\t{}\n", to_pascal_case(name)));
        }
    }
    out.push_str(")\n\n");

    generate_state_display_name(ir, out);
    generate_state_is_terminal(ir, out);
}

fn generate_state_display_name(ir: &WorkflowIR, out: &mut String) {
    out.push_str("func (s State) DisplayName() string {\n");
    out.push_str("\tswitch s {\n");
    for (name, state) in &ir.states {
        out.push_str(&format!(
            "\tcase {}:\n\t\treturn \"{}\"\n",
            to_pascal_case(name),
            state.display_name()
        ));
    }
    out.push_str("\tdefault:\n\t\tpanic(\"unreachable\")\n");
    out.push_str("\t}\n");
    out.push_str("}\n\n");
}

fn generate_state_is_terminal(ir: &WorkflowIR, out: &mut String) {
    out.push_str("func (s State) IsTerminal() bool {\n");
    let terminals: Vec<String> = ir
        .states
        .iter()
        .filter(|(_, s)| s.is_terminal())
        .map(|(name, _)| format!("\tcase {}:\n\t\treturn true", to_pascal_case(name)))
        .collect();
    if terminals.is_empty() {
        out.push_str("\treturn false\n");
    } else {
        out.push_str("\tswitch s {\n");
        for t in &terminals {
            out.push_str(t);
            out.push('\n');
        }
        out.push_str("\tdefault:\n\t\treturn false\n");
        out.push_str("\t}\n");
    }
    out.push_str("}\n\n");
}

fn generate_executor_type(out: &mut String) {
    out.push_str("type Executor int\n\n");
    out.push_str("const (\n");
    out.push_str("\tAgent Executor = iota\n");
    out.push_str("\tHuman\n");
    out.push_str(")\n\n");
}

fn generate_outcome_types(ir: &WorkflowIR, out: &mut String) {
    for (name, state) in &ir.states {
        if let StateDef::Action { prompt_name, .. } = state {
            if let Some(prompt) = ir.prompts.get(prompt_name) {
                let type_name = format!("{}Outcome", to_pascal_case(name));
                generate_single_outcome_type(&type_name, name, prompt, out);
            }
        }
    }
}

/// Returns the prefixed constant name for an outcome variant.
/// E.g., action "planning" + outcome "plan_complete" → "PlanningPlanComplete"
fn outcome_const_name(action_name: &str, outcome: &str) -> String {
    format!("{}{}", to_pascal_case(action_name), to_pascal_case(outcome))
}

fn generate_single_outcome_type(
    type_name: &str,
    action_name: &str,
    prompt: &crate::prompt::PromptFile,
    out: &mut String,
) {
    out.push_str(&format!("type {} int\n\n", type_name));
    out.push_str("const (\n");

    let outcomes: Vec<(&String, &String)> =
        prompt.success.iter().chain(prompt.failure.iter()).collect();

    for (i, (outcome, _)) in outcomes.iter().enumerate() {
        let const_name = outcome_const_name(action_name, outcome);
        if i == 0 {
            out.push_str(&format!("\t{} {} = iota\n", const_name, type_name));
        } else {
            out.push_str(&format!("\t{}\n", const_name));
        }
    }
    out.push_str(")\n\n");

    generate_outcome_target(type_name, action_name, prompt, out);
    generate_outcome_is_success(type_name, action_name, prompt, out);
}

fn generate_outcome_target(
    type_name: &str,
    action_name: &str,
    prompt: &crate::prompt::PromptFile,
    out: &mut String,
) {
    out.push_str(&format!("func (o {}) Target() State {{\n", type_name));
    out.push_str("\tswitch o {\n");
    for (outcome, target) in prompt.success.iter().chain(prompt.failure.iter()) {
        out.push_str(&format!(
            "\tcase {}:\n\t\treturn {}\n",
            outcome_const_name(action_name, outcome),
            to_pascal_case(target)
        ));
    }
    out.push_str("\tdefault:\n\t\tpanic(\"unreachable\")\n");
    out.push_str("\t}\n");
    out.push_str("}\n\n");
}

fn generate_outcome_is_success(
    type_name: &str,
    action_name: &str,
    prompt: &crate::prompt::PromptFile,
    out: &mut String,
) {
    out.push_str(&format!("func (o {}) IsSuccess() bool {{\n", type_name));
    if prompt.success.is_empty() {
        out.push_str("\treturn false\n");
    } else if prompt.success.len() == 1 {
        let name = outcome_const_name(action_name, prompt.success.keys().next().unwrap());
        out.push_str(&format!("\treturn o == {}\n", name));
    } else {
        out.push_str("\tswitch o {\n");
        for key in prompt.success.keys() {
            out.push_str(&format!(
                "\tcase {}:\n\t\treturn true\n",
                outcome_const_name(action_name, key)
            ));
        }
        out.push_str("\tdefault:\n\t\treturn false\n");
        out.push_str("\t}\n");
    }
    out.push_str("}\n\n");
}

fn generate_outcome_union(ir: &WorkflowIR, out: &mut String) {
    let actions = collect_actions_with_outcomes(ir);
    if actions.is_empty() {
        return;
    }

    out.push_str("// Outcome is a union type wrapping all action outcomes.\n");
    out.push_str("type Outcome struct {\n");
    out.push_str("\tAction string\n");
    out.push_str("\tValue  interface{}\n");
    out.push_str("}\n\n");

    // Constructor functions
    for (action_name, _) in &actions {
        let pascal = to_pascal_case(action_name);
        let type_name = format!("{}Outcome", pascal);
        out.push_str(&format!(
            "func New{}Outcome(o {}) Outcome {{\n",
            pascal, type_name
        ));
        out.push_str(&format!(
            "\treturn Outcome{{Action: \"{}\", Value: o}}\n",
            action_name
        ));
        out.push_str("}\n\n");
    }
}

fn generate_apply_fn(ir: &WorkflowIR, out: &mut String) {
    let actions = collect_actions_with_outcomes(ir);
    if actions.is_empty() {
        return;
    }

    out.push_str("func Apply(state State, outcome Outcome) (State, error) {\n");
    out.push_str("\tswitch state {\n");
    for (action_name, _) in &actions {
        let pascal = to_pascal_case(action_name);
        let type_name = format!("{}Outcome", pascal);
        out.push_str(&format!("\tcase {}:\n", pascal));
        out.push_str(&format!(
            "\t\tif o, ok := outcome.Value.({}); ok {{\n",
            type_name
        ));
        out.push_str("\t\t\treturn o.Target(), nil\n");
        out.push_str("\t\t}\n");
        out.push_str(&format!(
            "\t\treturn 0, fmt.Errorf(\"invalid outcome type for state {}\")\n",
            pascal
        ));
    }
    out.push_str("\tdefault:\n\t\treturn 0, fmt.Errorf(\"no transitions from state %d\", state)\n");
    out.push_str("\t}\n");
    out.push_str("}\n\n");
}

fn generate_profiles(ir: &WorkflowIR, out: &mut String) {
    generate_profile_struct(out);
    for profile in ir.profiles.values() {
        generate_single_profile(ir, profile, out);
    }
}

fn generate_profile_struct(out: &mut String) {
    out.push_str("type Profile struct {\n");
    out.push_str("\tID          string\n");
    out.push_str("\tDescription string\n");
    out.push_str("\tPhases      []string\n");
    out.push_str("\tOutputs     map[State]string\n");
    out.push_str("\tExecutors   map[State]Executor\n");
    out.push_str("}\n\n");
}

fn generate_single_profile(ir: &WorkflowIR, profile: &crate::ir::ProfileDef, out: &mut String) {
    let var_name = format!("Profile{}", to_pascal_case(&profile.name));
    let desc = profile.description.as_deref().unwrap_or("");

    out.push_str(&format!("var {} = Profile{{\n", var_name));
    out.push_str(&format!("\tID:          \"{}\",\n", profile.name));
    out.push_str(&format!("\tDescription: \"{}\",\n", desc));

    // Phases
    out.push_str("\tPhases:      []string{");
    for phase in &profile.phases {
        out.push_str(&format!("\"{}\"", phase));
        out.push_str(", ");
    }
    out.push_str("},\n");

    // Outputs
    out.push_str("\tOutputs:     map[State]string{");
    for phase_name in &profile.phases {
        if let Some(phase) = ir.phases.get(phase_name) {
            for step_name in [&phase.produce_step, &phase.gate_step] {
                if let Some(step) = ir.steps.get(step_name) {
                    if let Some(state) = ir.states.get(&step.action) {
                        let output = profile
                            .overrides
                            .get(&step.action)
                            .and_then(|o| o.output.as_ref())
                            .or_else(|| state.output());
                        if let Some(o) = output {
                            out.push_str(&format!(
                                "{}: \"{}\", ",
                                to_pascal_case(&step.action),
                                o.artifact_type
                            ));
                        }
                    }
                }
            }
        }
    }
    out.push_str("},\n");

    // Executors
    out.push_str("\tExecutors:   map[State]Executor{");
    for phase_name in &profile.phases {
        if let Some(phase) = ir.phases.get(phase_name) {
            for step_name in [&phase.produce_step, &phase.gate_step] {
                if let Some(step) = ir.steps.get(step_name) {
                    if let Some(state) = ir.states.get(&step.action) {
                        let executor = profile
                            .overrides
                            .get(&step.action)
                            .and_then(|o| o.executor)
                            .or_else(|| state.executor())
                            .unwrap_or(Executor::Agent);
                        let exec_str = match executor {
                            Executor::Agent => "Agent",
                            Executor::Human => "Human",
                        };
                        out.push_str(&format!("{}: {}, ", to_pascal_case(&step.action), exec_str));
                    }
                }
            }
        }
    }
    out.push_str("},\n");

    out.push_str("}\n\n");
}

fn generate_prompt_metadata(ir: &WorkflowIR, out: &mut String) {
    generate_param_types(out);
    generate_prompt_structs(out);
    for (prompt_name, prompt) in &ir.prompts {
        generate_single_prompt(prompt_name, prompt, out);
    }
}

fn generate_param_types(out: &mut String) {
    out.push_str("type ParamType int\n\n");
    out.push_str("const (\n");
    out.push_str("\tParamString ParamType = iota\n");
    out.push_str("\tParamInt\n");
    out.push_str("\tParamBool\n");
    out.push_str("\tParamEnum\n");
    out.push_str(")\n\n");
}

fn generate_prompt_structs(out: &mut String) {
    out.push_str("type ParamDef struct {\n");
    out.push_str("\tName        string\n");
    out.push_str("\tType        ParamType\n");
    out.push_str("\tRequired    bool\n");
    out.push_str("\tDescription string\n");
    out.push_str("}\n\n");

    out.push_str("type OutcomeMeta struct {\n");
    out.push_str("\tName      string\n");
    out.push_str("\tTarget    State\n");
    out.push_str("\tIsSuccess bool\n");
    out.push_str("}\n\n");

    out.push_str("type PromptMeta struct {\n");
    out.push_str("\tName     string\n");
    out.push_str("\tAccept   []string\n");
    out.push_str("\tParams   []ParamDef\n");
    out.push_str("\tOutcomes []OutcomeMeta\n");
    out.push_str("\tBody     string\n");
    out.push_str("}\n\n");
}

fn generate_single_prompt(prompt_name: &str, prompt: &crate::prompt::PromptFile, out: &mut String) {
    let var_name = format!("Prompt{}", to_pascal_case(prompt_name));
    out.push_str(&format!("var {} = PromptMeta{{\n", var_name));
    out.push_str(&format!("\tName: \"{}\",\n", prompt_name));

    // Accept
    out.push_str("\tAccept: []string{");
    for criteria in &prompt.accept {
        let escaped = criteria.replace('"', "\\\"");
        out.push_str(&format!("\"{}\"", escaped));
        out.push_str(", ");
    }
    out.push_str("},\n");

    // Params
    out.push_str("\tParams: []ParamDef{");
    for (param_name, param_def) in &prompt.params {
        let pt = match param_def.param_type {
            ParamType::String => "ParamString",
            ParamType::Int => "ParamInt",
            ParamType::Bool => "ParamBool",
            ParamType::Enum => "ParamEnum",
        };
        let desc = param_def.description.as_deref().unwrap_or("");
        let desc_escaped = desc.replace('"', "\\\"");
        out.push_str(&format!(
            "{{Name: \"{}\", Type: {}, Required: {}, Description: \"{}\"}}, ",
            param_name, pt, param_def.required, desc_escaped
        ));
    }
    out.push_str("},\n");

    // Outcomes
    out.push_str("\tOutcomes: []OutcomeMeta{");
    for (outcome, target) in &prompt.success {
        out.push_str(&format!(
            "{{Name: \"{}\", Target: {}, IsSuccess: true}}, ",
            outcome,
            to_pascal_case(target)
        ));
    }
    for (outcome, target) in &prompt.failure {
        out.push_str(&format!(
            "{{Name: \"{}\", Target: {}, IsSuccess: false}}, ",
            outcome,
            to_pascal_case(target)
        ));
    }
    out.push_str("},\n");

    // Body
    let body_escaped = prompt
        .body
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n");
    out.push_str(&format!("\tBody: \"{}\",\n", body_escaped));
    out.push_str("}\n\n");
}

fn collect_actions_with_outcomes(ir: &WorkflowIR) -> Vec<(&str, &str)> {
    ir.states
        .iter()
        .filter_map(|(name, state)| {
            if let StateDef::Action { prompt_name, .. } = state {
                if ir.prompts.contains_key(prompt_name) {
                    Some((name.as_str(), prompt_name.as_str()))
                } else {
                    None
                }
            } else {
                None
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::lower::lower;
    use crate::parse;
    use std::path::PathBuf;

    fn fixture_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/knots_sdlc")
    }

    #[test]
    fn test_generate_go_state_type() {
        let input = std::fs::read_to_string(fixture_dir().join("workflow.loom")).unwrap();
        let ast = parse::parse_workflow(&input).unwrap();
        let (ir, _) = lower(&ast, &fixture_dir()).unwrap();
        let code = generate(&ir);

        assert!(code.contains("type State int"));
        assert!(code.contains("ReadyForPlanning"));
        assert!(code.contains("Planning"));
    }

    #[test]
    fn test_generate_go_outcome_types() {
        let input = std::fs::read_to_string(fixture_dir().join("workflow.loom")).unwrap();
        let ast = parse::parse_workflow(&input).unwrap();
        let (ir, _) = lower(&ast, &fixture_dir()).unwrap();
        let code = generate(&ir);

        assert!(code.contains("type PlanningOutcome int"));
        assert!(code.contains("PlanningPlanComplete PlanningOutcome = iota"));
        assert!(code.contains("func (o PlanningOutcome) Target() State {"));
        assert!(code.contains("func (o PlanningOutcome) IsSuccess() bool {"));
        assert!(code.contains("return o == PlanningPlanComplete"));
    }

    #[test]
    fn test_generate_go_executor() {
        let input = std::fs::read_to_string(fixture_dir().join("workflow.loom")).unwrap();
        let ast = parse::parse_workflow(&input).unwrap();
        let (ir, _) = lower(&ast, &fixture_dir()).unwrap();
        let code = generate(&ir);

        assert!(code.contains("type Executor int"));
        assert!(code.contains("Agent Executor = iota"));
        assert!(code.contains("Human"));
        assert!(!code.contains("OutputKind"));
    }

    #[test]
    fn test_generate_go_profiles() {
        let input = std::fs::read_to_string(fixture_dir().join("workflow.loom")).unwrap();
        let ast = parse::parse_workflow(&input).unwrap();
        let (ir, _) = lower(&ast, &fixture_dir()).unwrap();
        let code = generate(&ir);

        assert!(code.contains("type Profile struct {"));
        assert!(code.contains("var ProfileAutopilot = Profile{"));
    }

    #[test]
    fn test_generate_go_apply_fn() {
        let input = std::fs::read_to_string(fixture_dir().join("workflow.loom")).unwrap();
        let ast = parse::parse_workflow(&input).unwrap();
        let (ir, _) = lower(&ast, &fixture_dir()).unwrap();
        let code = generate(&ir);

        assert!(code.contains("func Apply(state State, outcome Outcome) (State, error) {"));
        assert!(code.contains("type Outcome struct {"));
    }

    #[test]
    fn test_generate_go_prompt_metadata() {
        let input = std::fs::read_to_string(fixture_dir().join("workflow.loom")).unwrap();
        let ast = parse::parse_workflow(&input).unwrap();
        let (ir, _) = lower(&ast, &fixture_dir()).unwrap();
        let code = generate(&ir);

        assert!(code.contains("type PromptMeta struct {"));
        assert!(code.contains("type ParamDef struct {"));
        assert!(code.contains("type OutcomeMeta struct {"));
        assert!(code.contains("var PromptPlanning = PromptMeta{"));
        assert!(code.contains("ParamEnum"));
    }

    #[test]
    fn test_generate_go_package_header() {
        let input = std::fs::read_to_string(fixture_dir().join("workflow.loom")).unwrap();
        let ast = parse::parse_workflow(&input).unwrap();
        let (ir, _) = lower(&ast, &fixture_dir()).unwrap();
        let code = generate(&ir);

        assert!(code.contains("package workflow"));
        assert!(code.contains("// Generated by loom v0.1.0 from knots_sdlc v1"));
    }
}
