use crate::ir::{StateDef, WorkflowIR};
use crate::parse::ast::{Executor, OutputKind};
use crate::prompt::ParamType;

/// Generate Python code from the workflow IR
#[allow(dead_code)]
pub fn generate(ir: &WorkflowIR) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "# Generated by loom v0.1.0 from {} v{}\n\n",
        ir.name, ir.version
    ));

    out.push_str("from __future__ import annotations\n");
    out.push_str("from enum import Enum\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from typing import Union\n\n\n");

    generate_state_enum(ir, &mut out);
    generate_executor_enum(&mut out);
    generate_output_kind_enum(&mut out);
    generate_outcome_enums(ir, &mut out);
    generate_outcome_union(ir, &mut out);
    generate_transition_fn(ir, &mut out);
    generate_param_types(&mut out);
    generate_profile_class(ir, &mut out);
    generate_prompt_metadata(ir, &mut out);

    out
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase(),
            }
        })
        .collect()
}

fn to_upper_snake(s: &str) -> String {
    s.to_uppercase()
}

fn generate_state_enum(ir: &WorkflowIR, out: &mut String) {
    out.push_str("class State(Enum):\n");
    for (i, name) in ir.states.keys().enumerate() {
        out.push_str(&format!("    {} = {}\n", to_upper_snake(name), i));
    }
    out.push('\n');

    // display_name property
    out.push_str("    @property\n");
    out.push_str("    def display_name(self) -> str:\n");
    out.push_str("        return {\n");
    for (name, state) in &ir.states {
        out.push_str(&format!(
            "            State.{}: \"{}\",\n",
            to_upper_snake(name),
            state.display_name()
        ));
    }
    out.push_str("        }[self]\n\n");

    // is_terminal property
    out.push_str("    @property\n");
    out.push_str("    def is_terminal(self) -> bool:\n");
    let terminals: Vec<String> = ir
        .states
        .iter()
        .filter(|(_, s)| s.is_terminal())
        .map(|(name, _)| format!("State.{}", to_upper_snake(name)))
        .collect();
    if terminals.is_empty() {
        out.push_str("        return False\n");
    } else {
        out.push_str(&format!(
            "        return self in ({})\n",
            terminals.join(", ")
        ));
    }
    out.push_str("\n\n");
}

fn generate_executor_enum(out: &mut String) {
    out.push_str("class Executor(Enum):\n");
    out.push_str("    AGENT = 0\n");
    out.push_str("    HUMAN = 1\n");
    out.push_str("\n\n");
}

fn generate_output_kind_enum(out: &mut String) {
    out.push_str("class OutputKind(Enum):\n");
    out.push_str("    LOCAL = 0\n");
    out.push_str("    REMOTE = 1\n");
    out.push_str("    REMOTE_MAIN = 2\n");
    out.push_str("    PR = 3\n");
    out.push_str("\n\n");
}

fn generate_outcome_enums(ir: &WorkflowIR, out: &mut String) {
    for (name, state) in &ir.states {
        if let StateDef::Action { prompt_name, .. } = state {
            if let Some(prompt) = ir.prompts.get(prompt_name) {
                let class_name = format!("{}Outcome", to_pascal_case(name));

                out.push_str(&format!("class {}(Enum):\n", class_name));
                for (i, outcome) in prompt
                    .success
                    .keys()
                    .chain(prompt.failure.keys())
                    .enumerate()
                {
                    out.push_str(&format!(
                        "    {} = {}\n",
                        to_upper_snake(outcome),
                        i
                    ));
                }
                out.push('\n');

                // target() method
                generate_outcome_target_method(prompt, &mut *out);

                // is_success() method
                generate_outcome_is_success_method(prompt, &class_name, &mut *out);

                out.push('\n');
            }
        }
    }
}

fn generate_outcome_target_method(
    prompt: &crate::prompt::PromptFile,
    out: &mut String,
) {
    out.push_str("    def target(self) -> State:\n");
    out.push_str("        return {\n");
    for (outcome, target) in prompt.success.iter().chain(prompt.failure.iter()) {
        out.push_str(&format!(
            "            self.__class__.{}: State.{},\n",
            to_upper_snake(outcome),
            to_upper_snake(target)
        ));
    }
    out.push_str("        }[self]\n\n");
}

fn generate_outcome_is_success_method(
    prompt: &crate::prompt::PromptFile,
    class_name: &str,
    out: &mut String,
) {
    out.push_str("    def is_success(self) -> bool:\n");
    if prompt.success.is_empty() {
        out.push_str("        return False\n");
    } else {
        let success_members: Vec<String> = prompt
            .success
            .keys()
            .map(|k| format!("{}.{}", class_name, to_upper_snake(k)))
            .collect();
        out.push_str(&format!(
            "        return self in ({})\n",
            success_members.join(", ")
        ));
    }
}

fn generate_outcome_union(ir: &WorkflowIR, out: &mut String) {
    let action_names: Vec<String> = ir
        .states
        .iter()
        .filter_map(|(name, state)| {
            if let StateDef::Action { prompt_name, .. } = state {
                if ir.prompts.contains_key(prompt_name) {
                    Some(name.clone())
                } else {
                    None
                }
            } else {
                None
            }
        })
        .collect();

    if action_names.is_empty() {
        return;
    }

    let types: Vec<String> = action_names
        .iter()
        .map(|n| format!("{}Outcome", to_pascal_case(n)))
        .collect();
    out.push_str(&format!("Outcome = Union[{}]\n\n\n", types.join(", ")));
}

fn generate_transition_fn(ir: &WorkflowIR, out: &mut String) {
    let actions_with_outcomes: Vec<(&str, &str)> = ir
        .states
        .iter()
        .filter_map(|(name, state)| {
            if let StateDef::Action { prompt_name, .. } = state {
                if ir.prompts.contains_key(prompt_name) {
                    Some((name.as_str(), prompt_name.as_str()))
                } else {
                    None
                }
            } else {
                None
            }
        })
        .collect();

    if actions_with_outcomes.is_empty() {
        return;
    }

    out.push_str("def apply(state: State, outcome: Outcome) -> State:\n");
    out.push_str("    \"\"\"Apply an outcome to a state, returning the new state.\"\"\"\n");
    out.push_str("    valid = {\n");
    for (action_name, _) in &actions_with_outcomes {
        let outcome_class = format!("{}Outcome", to_pascal_case(action_name));
        out.push_str(&format!(
            "        State.{}: {},\n",
            to_upper_snake(action_name),
            outcome_class
        ));
    }
    out.push_str("    }\n");
    out.push_str("    expected = valid.get(state)\n");
    out.push_str("    if expected is None or not isinstance(outcome, expected):\n");
    out.push_str(
        "        raise ValueError(f\"Invalid outcome {{outcome!r}} for state {{state!r}}\")\n",
    );
    out.push_str("    return outcome.target()\n\n\n");
}

fn generate_param_types(out: &mut String) {
    out.push_str("class ParamType(Enum):\n");
    out.push_str("    STRING = 0\n");
    out.push_str("    INT = 1\n");
    out.push_str("    BOOL = 2\n");
    out.push_str("    ENUM = 3\n");
    out.push_str("\n\n");

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class ParamDef:\n");
    out.push_str("    name: str\n");
    out.push_str("    param_type: ParamType\n");
    out.push_str("    required: bool\n");
    out.push_str("    description: str\n");
    out.push_str("\n\n");

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class OutcomeMeta:\n");
    out.push_str("    name: str\n");
    out.push_str("    target: State\n");
    out.push_str("    is_success: bool\n");
    out.push_str("\n\n");

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class PromptMeta:\n");
    out.push_str("    name: str\n");
    out.push_str("    accept: tuple[str, ...]\n");
    out.push_str("    params: tuple[ParamDef, ...]\n");
    out.push_str("    outcomes: tuple[OutcomeMeta, ...]\n");
    out.push_str("    body: str\n");
    out.push_str("\n\n");
}

fn generate_profile_class(ir: &WorkflowIR, out: &mut String) {
    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class Profile:\n");
    out.push_str("    id: str\n");
    out.push_str("    description: str\n");
    out.push_str("    phases: tuple[str, ...]\n");
    out.push_str("    output: OutputKind\n");
    out.push_str("    executors: tuple[tuple[State, Executor], ...]\n");
    out.push_str("\n\n");

    for profile in ir.profiles.values() {
        let var_name = profile.name.to_uppercase();
        let desc = profile.description.as_deref().unwrap_or("");
        let output = match profile.output.unwrap_or(OutputKind::Local) {
            OutputKind::Local => "OutputKind.LOCAL",
            OutputKind::Remote => "OutputKind.REMOTE",
            OutputKind::RemoteMain => "OutputKind.REMOTE_MAIN",
            OutputKind::Pr => "OutputKind.PR",
        };

        out.push_str(&format!("{} = Profile(\n", var_name));
        out.push_str(&format!("    id=\"{}\",\n", profile.name));
        out.push_str(&format!("    description=\"{}\",\n", desc));

        // Phases
        out.push_str("    phases=(");
        for phase in &profile.phases {
            out.push_str(&format!("\"{}\", ", phase));
        }
        out.push_str("),\n");

        out.push_str(&format!("    output={},\n", output));

        // Executor overrides
        out.push_str("    executors=(");
        for phase_name in &profile.phases {
            if let Some(phase) = ir.phases.get(phase_name) {
                for step_name in [&phase.produce_step, &phase.gate_step] {
                    if let Some(step) = ir.steps.get(step_name) {
                        if let Some(state) = ir.states.get(&step.action) {
                            let executor = profile
                                .overrides
                                .get(&step.action)
                                .copied()
                                .or_else(|| state.executor())
                                .unwrap_or(Executor::Agent);
                            let exec_str = match executor {
                                Executor::Agent => "Executor.AGENT",
                                Executor::Human => "Executor.HUMAN",
                            };
                            out.push_str(&format!(
                                "(State.{}, {}), ",
                                to_upper_snake(&step.action),
                                exec_str
                            ));
                        }
                    }
                }
            }
        }
        out.push_str("),\n");
        out.push_str(")\n\n");
    }
    out.push('\n');
}

fn generate_prompt_metadata(ir: &WorkflowIR, out: &mut String) {
    for (prompt_name, prompt) in &ir.prompts {
        let var_name = format!("PROMPT_{}", prompt_name.to_uppercase());
        out.push_str(&format!("{} = PromptMeta(\n", var_name));
        out.push_str(&format!("    name=\"{}\",\n", prompt_name));

        // Accept
        out.push_str("    accept=(");
        for criteria in &prompt.accept {
            let escaped = criteria.replace('\\', "\\\\").replace('"', "\\\"");
            out.push_str(&format!("\"{}\", ", escaped));
        }
        out.push_str("),\n");

        // Params
        out.push_str("    params=(");
        for (param_name, param_def) in &prompt.params {
            let pt = match param_def.param_type {
                ParamType::String => "ParamType.STRING",
                ParamType::Int => "ParamType.INT",
                ParamType::Bool => "ParamType.BOOL",
                ParamType::Enum => "ParamType.ENUM",
            };
            let desc = param_def.description.as_deref().unwrap_or("");
            let desc_escaped = desc.replace('\\', "\\\\").replace('"', "\\\"");
            out.push_str(&format!(
                "ParamDef(name=\"{}\", param_type={}, required={}, description=\"{}\"), ",
                param_name,
                pt,
                if param_def.required { "True" } else { "False" },
                desc_escaped
            ));
        }
        out.push_str("),\n");

        // Outcomes
        out.push_str("    outcomes=(");
        for (outcome, target) in &prompt.success {
            out.push_str(&format!(
                "OutcomeMeta(name=\"{}\", target=State.{}, is_success=True), ",
                outcome,
                to_upper_snake(target)
            ));
        }
        for (outcome, target) in &prompt.failure {
            out.push_str(&format!(
                "OutcomeMeta(name=\"{}\", target=State.{}, is_success=False), ",
                outcome,
                to_upper_snake(target)
            ));
        }
        out.push_str("),\n");

        // Body
        let body_escaped = prompt
            .body
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n");
        out.push_str(&format!("    body=\"{}\",\n", body_escaped));
        out.push_str(")\n\n");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::lower::lower;
    use crate::parse;
    use std::path::PathBuf;

    fn fixture_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/knots_sdlc")
    }

    #[test]
    fn test_generate_python() {
        let input = std::fs::read_to_string(fixture_dir().join("workflow.loom")).unwrap();
        let ast = parse::parse_workflow(&input).unwrap();
        let (ir, _) = lower(&ast, &fixture_dir()).unwrap();
        let code = generate(&ir);

        // Header
        assert!(code.contains("# Generated by loom v0.1.0 from"));
        assert!(code.contains("from __future__ import annotations"));
        assert!(code.contains("from enum import Enum"));
        assert!(code.contains("from dataclasses import dataclass"));

        // State enum
        assert!(code.contains("class State(Enum):"));
        assert!(code.contains("READY_FOR_PLANNING"));
        assert!(code.contains("def display_name(self) -> str:"));
        assert!(code.contains("def is_terminal(self) -> bool:"));

        // Outcome enums
        assert!(code.contains("class PlanningOutcome(Enum):"));
        assert!(code.contains("PLAN_COMPLETE"));

        // Outcome methods
        assert!(code.contains("def target(self) -> State:"));
        assert!(code.contains("def is_success(self) -> bool:"));

        // Executor and OutputKind
        assert!(code.contains("class Executor(Enum):"));
        assert!(code.contains("class OutputKind(Enum):"));

        // Profile
        assert!(code.contains("AUTOPILOT = Profile("));

        // Transition function
        assert!(code.contains("def apply(state: State, outcome: Outcome) -> State:"));

        // Outcome union
        assert!(code.contains("Outcome = Union["));

        // Prompt metadata
        assert!(code.contains("class PromptMeta:"));
        assert!(code.contains("class ParamDef:"));
        assert!(code.contains("ParamType.ENUM"));
        assert!(code.contains("PROMPT_PLANNING = PromptMeta("));
    }
}
