use crate::ir::{StateDef, WorkflowIR};
use crate::parse::ast::{Executor, OutputKind};

/// Generate Rust code from the workflow IR
pub fn generate(ir: &WorkflowIR) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "// Generated by loom v0.1.0 from {} v{}\n\n",
        ir.name, ir.version
    ));

    generate_state_enum(ir, &mut out);
    generate_executor_enum(&mut out);
    generate_output_kind_enum(&mut out);
    generate_outcome_enums(ir, &mut out);
    generate_profiles(ir, &mut out);
    generate_prompt_metadata(ir, &mut out);

    out
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase(),
            }
        })
        .collect()
}

fn generate_state_enum(ir: &WorkflowIR, out: &mut String) {
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    out.push_str("pub enum State {\n");
    for name in ir.states.keys() {
        out.push_str(&format!("    {},\n", to_pascal_case(name)));
    }
    out.push_str("}\n\n");

    // Display impl
    out.push_str("impl State {\n");
    out.push_str("    pub fn display_name(&self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for (name, state) in &ir.states {
        out.push_str(&format!(
            "            State::{} => \"{}\",\n",
            to_pascal_case(name),
            state.display_name()
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    out.push_str("    pub fn is_terminal(&self) -> bool {\n");
    out.push_str("        matches!(self, ");
    let terminals: Vec<String> = ir.states.iter()
        .filter(|(_, s)| s.is_terminal())
        .map(|(name, _)| format!("State::{}", to_pascal_case(name)))
        .collect();
    if terminals.is_empty() {
        out.push_str("_ if false => true");
    } else {
        out.push_str(&terminals.join(" | "));
    }
    out.push_str(")\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn generate_executor_enum(out: &mut String) {
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum Executor {\n");
    out.push_str("    Agent,\n");
    out.push_str("    Human,\n");
    out.push_str("}\n\n");
}

fn generate_output_kind_enum(out: &mut String) {
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum OutputKind {\n");
    out.push_str("    Local,\n");
    out.push_str("    Remote,\n");
    out.push_str("    RemoteMain,\n");
    out.push_str("    Pr,\n");
    out.push_str("}\n\n");
}

fn generate_outcome_enums(ir: &WorkflowIR, out: &mut String) {
    for (name, state) in &ir.states {
        if let StateDef::Action { prompt_name, .. } = state {
            if let Some(prompt) = ir.prompts.get(prompt_name) {
                let enum_name = format!("{}Outcome", to_pascal_case(name));

                out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
                out.push_str(&format!("pub enum {} {{\n", enum_name));

                for outcome in prompt.success.keys().chain(prompt.failure.keys()) {
                    out.push_str(&format!("    {},\n", to_pascal_case(outcome)));
                }
                out.push_str("}\n\n");

                // target() method
                out.push_str(&format!("impl {} {{\n", enum_name));
                out.push_str("    pub fn target(&self) -> State {\n");
                out.push_str("        match self {\n");
                for (outcome, target) in prompt.success.iter().chain(prompt.failure.iter()) {
                    out.push_str(&format!(
                        "            Self::{} => State::{},\n",
                        to_pascal_case(outcome),
                        to_pascal_case(target)
                    ));
                }
                out.push_str("        }\n");
                out.push_str("    }\n\n");

                // is_success() method
                out.push_str("    pub fn is_success(&self) -> bool {\n");
                if prompt.success.is_empty() {
                    out.push_str("        false\n");
                } else {
                    out.push_str("        matches!(self, ");
                    let success_variants: Vec<String> = prompt.success.keys()
                        .map(|k| format!("Self::{}", to_pascal_case(k)))
                        .collect();
                    out.push_str(&success_variants.join(" | "));
                    out.push_str(")\n");
                }
                out.push_str("    }\n");
                out.push_str("}\n\n");
            }
        }
    }
}

fn generate_profiles(ir: &WorkflowIR, out: &mut String) {
    out.push_str("pub struct Profile {\n");
    out.push_str("    pub id: &'static str,\n");
    out.push_str("    pub description: &'static str,\n");
    out.push_str("    pub phases: &'static [&'static str],\n");
    out.push_str("    pub output: OutputKind,\n");
    out.push_str("    pub executors: &'static [(State, Executor)],\n");
    out.push_str("}\n\n");

    for profile in ir.profiles.values() {
        let var_name = profile.name.to_uppercase();
        let desc = profile.description.as_deref().unwrap_or("");
        let output = match profile.output.unwrap_or(OutputKind::Local) {
            OutputKind::Local => "OutputKind::Local",
            OutputKind::Remote => "OutputKind::Remote",
            OutputKind::RemoteMain => "OutputKind::RemoteMain",
            OutputKind::Pr => "OutputKind::Pr",
        };

        out.push_str(&format!("pub const {}: Profile = Profile {{\n", var_name));
        out.push_str(&format!("    id: \"{}\",\n", profile.name));
        out.push_str(&format!("    description: \"{}\",\n", desc));

        // Phases
        out.push_str("    phases: &[");
        for phase in &profile.phases {
            out.push_str(&format!("\"{}\"", phase));
            out.push_str(", ");
        }
        out.push_str("],\n");

        out.push_str(&format!("    output: {},\n", output));

        // Executor overrides - build the full executor map for all actions in profile's phases
        out.push_str("    executors: &[");
        for phase_name in &profile.phases {
            if let Some(phase) = ir.phases.get(phase_name) {
                for step_name in [&phase.produce_step, &phase.gate_step] {
                    if let Some(step) = ir.steps.get(step_name) {
                        if let Some(state) = ir.states.get(&step.action) {
                            let executor = profile.overrides.get(&step.action)
                                .copied()
                                .or_else(|| state.executor())
                                .unwrap_or(Executor::Agent);
                            let exec_str = match executor {
                                Executor::Agent => "Executor::Agent",
                                Executor::Human => "Executor::Human",
                            };
                            out.push_str(&format!(
                                "(State::{}, {}), ",
                                to_pascal_case(&step.action),
                                exec_str
                            ));
                        }
                    }
                }
            }
        }
        out.push_str("],\n");

        out.push_str("};\n\n");
    }
}

fn generate_prompt_metadata(ir: &WorkflowIR, out: &mut String) {
    out.push_str("pub struct PromptMeta {\n");
    out.push_str("    pub name: &'static str,\n");
    out.push_str("    pub accept: &'static [&'static str],\n");
    out.push_str("    pub body: &'static str,\n");
    out.push_str("}\n\n");

    for (prompt_name, prompt) in &ir.prompts {
        let var_name = format!("PROMPT_{}", prompt_name.to_uppercase());
        out.push_str(&format!("pub const {}: PromptMeta = PromptMeta {{\n", var_name));
        out.push_str(&format!("    name: \"{}\",\n", prompt_name));
        out.push_str("    accept: &[");
        for criteria in &prompt.accept {
            let escaped = criteria.replace('"', "\\\"");
            out.push_str(&format!("\"{}\", ", escaped));
        }
        out.push_str("],\n");
        let body_escaped = prompt.body.replace('\\', "\\\\").replace('"', "\\\"");
        out.push_str(&format!("    body: \"{}\",\n", body_escaped));
        out.push_str("};\n\n");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::lower::lower;
    use crate::parse;
    use std::path::PathBuf;

    fn fixture_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/knots_sdlc")
    }

    #[test]
    fn test_generate_rust() {
        let input = std::fs::read_to_string(fixture_dir().join("workflow.loom")).unwrap();
        let ast = parse::parse_workflow(&input).unwrap();
        let (ir, _) = lower(&ast, &fixture_dir()).unwrap();
        let code = generate(&ir);

        assert!(code.contains("pub enum State {"));
        assert!(code.contains("ReadyForPlanning"));
        assert!(code.contains("pub enum PlanningOutcome {"));
        assert!(code.contains("PlanComplete"));
        assert!(code.contains("pub const AUTOPILOT: Profile"));
    }
}
